FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /source
COPY . .
RUN dotnet restore "PMS.Entities/PMS.Entities.csproj" --disable-parallel
RUN dotnet publish "PMS.Entities/PMS.Entities.csproj" -c Release -o /app/build
RUN dotnet restore "PMS.Services/PMS.Services.csproj" --disable-parallel
RUN dotnet publish "PMS.Services/PMS.Services.csproj" -c Release -o /app/build
RUN dotnet restore "PMS.API/PMS.API.csproj" --disable-parallel
RUN dotnet publish "PMS.API/PMS.API.csproj" -c Release -o /app/build


FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /app
COPY --from=base /app ./
EXPOSE 5000
ENTRYPOINT ["dotnet", "PMS.API.dll"]


# docker run --rm -p 5000:5000 -p 5001:5001 -e ASPNETCORE_HTTP_PORT=https://+:5001 -e ASPNETCORE_URLS=http://+:5000 pms