FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

WORKDIR /app
EXPOSE 5000
ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
# COPY ALL .csproj FILES
COPY "PMS.API/PMS.API.csproj" "PMS.API/PMS.API.csproj"
COPY "PMS.DTOs/PMS.DTOs.csproj" "PMS.DTOs/PMS.DTOs.csproj"
COPY "PMS.Services/PMS.Services.csproj" "PMS.Services/PMS.Services.csproj"
COPY "PMS.Entities/PMS.Entities.csproj" "PMS.Services/PMS.Entities.csproj"
# RESTORE PACKAGES
RUN dotnet restore "PMS.API/PMS.API.csproj"
# COPY EVERYTHING ELSE
COPY . .
RUN dotnet build "PMS.API/PMS.API.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "PMS.API/PMS.API.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "PMS.API.dll"]


# docker run --rm -p 5000:5000 -p 5001:5001 -e ASPNETCORE_HTTP_PORT=https://+:5001 -e ASPNETCORE_URLS=http://+:5000 pms